//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luveck.Service.Security.Utils.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Luveck.Service.Security.Utils.Resource.GeneralMessage", typeof(GeneralMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI o Correo electronico ya esta registrado.
        /// </summary>
        public static string DataRegistered {
            get {
                return ResourceManager.GetString("DataRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electronico ya esta siendo usado por otro usuario..
        /// </summary>
        public static string EmialUsed {
            get {
                return ResourceManager.GetString("EmialUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Interno.
        /// </summary>
        public static string Error500 {
            get {
                return ResourceManager.GetString("Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presento un error creando el usuario..
        /// </summary>
        public static string ErrorRegistrando {
            get {
                return ResourceManager.GetString("ErrorRegistrando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado la solicitud de cambio de contraseña al correo .
        /// </summary>
        public static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo completar el requerimiento..
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El modulo se creo exitosamente..
        /// </summary>
        public static string ModuleCreate {
            get {
                return ResourceManager.GetString("ModuleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El modulo a crear ya existe.
        /// </summary>
        public static string ModuleExist {
            get {
                return ResourceManager.GetString("ModuleExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña se ha cambiado correctamente..
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Role se creo de manera exitosa.
        /// </summary>
        public static string RoleCreate {
            get {
                return ResourceManager.GetString("RoleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Role que desea crear ya existe.
        /// </summary>
        public static string RoleExist {
            get {
                return ResourceManager.GetString("RoleExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El role seleccionado no existe..
        /// </summary>
        public static string RoleNoExist {
            get {
                return ResourceManager.GetString("RoleNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se actualizó el role..
        /// </summary>
        public static string RoleUpdated {
            get {
                return ResourceManager.GetString("RoleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario registrado correctamente..
        /// </summary>
        public static string SuccesRegister {
            get {
                return ResourceManager.GetString("SuccesRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario bloqueado por intentos no validos..
        /// </summary>
        public static string UserBloqValid {
            get {
                return ResourceManager.GetString("UserBloqValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información proporcionada es incorrecta..
        /// </summary>
        public static string UserNoExist {
            get {
                return ResourceManager.GetString("UserNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo y contraseña del usuario no válidos..
        /// </summary>
        public static string UserNoValid {
            get {
                return ResourceManager.GetString("UserNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se actualizaron los datos de usuario correctamente..
        /// </summary>
        public static string UserUpdate {
            get {
                return ResourceManager.GetString("UserUpdate", resourceCulture);
            }
        }
    }
}
