//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luveck.Service.Administration.Utils.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Luveck.Service.Administration.Utils.Resource.GeneralMessage", typeof(GeneralMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La categoria ya existe..
        /// </summary>
        public static string CategoryExist {
            get {
                return ResourceManager.GetString("CategoryExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La categoria indicada no existe..
        /// </summary>
        public static string CategoryNoExist {
            get {
                return ResourceManager.GetString("CategoryNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ciudad que intenta registrar ya existe..
        /// </summary>
        public static string CityExist {
            get {
                return ResourceManager.GetString("CityExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ciudad seleccionada no existe..
        /// </summary>
        public static string CityNoExist {
            get {
                return ResourceManager.GetString("CityNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El pais ya existe..
        /// </summary>
        public static string CountryExist {
            get {
                return ResourceManager.GetString("CountryExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El pais seleccionado no existe..
        /// </summary>
        public static string CountryNoExist {
            get {
                return ResourceManager.GetString("CountryNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El departamente ya existe..
        /// </summary>
        public static string DepartmentExist {
            get {
                return ResourceManager.GetString("DepartmentExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El departamento seleccionado no existe..
        /// </summary>
        public static string DepartmentNoExist {
            get {
                return ResourceManager.GetString("DepartmentNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error interno.
        /// </summary>
        public static string Error500 {
            get {
                return ResourceManager.GetString("Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El medico ya existe en sistema..
        /// </summary>
        public static string MedicalExist {
            get {
                return ResourceManager.GetString("MedicalExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El medico seleccionado no exite..
        /// </summary>
        public static string MedicalNoExist {
            get {
                return ResourceManager.GetString("MedicalNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La patologia ingresada ya existe..
        /// </summary>
        public static string PatologyExist {
            get {
                return ResourceManager.GetString("PatologyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La patologia seleccionada no existe..
        /// </summary>
        public static string PatologyNoExist {
            get {
                return ResourceManager.GetString("PatologyNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La farmacia ya existe..
        /// </summary>
        public static string PharmacyExist {
            get {
                return ResourceManager.GetString("PharmacyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La farmacia indicada no existe..
        /// </summary>
        public static string PharmacyNoExist {
            get {
                return ResourceManager.GetString("PharmacyNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto que desea registrar ya existe..
        /// </summary>
        public static string ProductExist {
            get {
                return ResourceManager.GetString("ProductExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto seleccionado no existe..
        /// </summary>
        public static string ProductNoExist {
            get {
                return ResourceManager.GetString("ProductNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La factura que desea registrar ya existe..
        /// </summary>
        public static string PurchaseExist {
            get {
                return ResourceManager.GetString("PurchaseExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La factura buscada no existe..
        /// </summary>
        public static string PurchaseNoExist {
            get {
                return ResourceManager.GetString("PurchaseNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La regla que intenta modificar no existe.
        /// </summary>
        public static string RuleNoExist {
            get {
                return ResourceManager.GetString("RuleNoExist", resourceCulture);
            }
        }
    }
}
